import { 
  Box, 
  Button, 
  Flex, 
  FormControl, 
  FormHelperText, 
  FormLabel, 
  Heading, 
  Input, 
  Textarea
 } from "@chakra-ui/react";
import Head from "next/head";
import { FormEvent, FunctionComponent, useState } from "react";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from 'yup';

interface IUserFormData{
    firstName:string,
    lastName:string,
    email:string,
    address:string,
    phone:string,
    description:string,
}

const schema = yup.object({
   firstName: yup.string().required(),
   lastName: yup.string().required(),
   email: yup.string(). required(),
   address: yup.string().required(),
   phone: yup.string().required(),
   description: yup.string().required(),
});

const Cadastro: FunctionComponent = () => {
    const {
        register,
        handleSubmit,
         formState: {errors}
        } = useForm <IUserFormData> ({
        resolver: yupResolver(schema)
    });

    function onSubmit (data: any){
        console.log(data)
    }

    //function setErros(error: any){
    //    console.log('Errors', error)
    //}
 
  return (
    <>
      <Head>
        <title>Formulário com NextJs e Chacka UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex
          minHeight='100vh'
          width='full'
          align='center'
          justify='center'
          background='gray.900'

        >
          <Box
            px={12}
            py={12}
            width='full'
            maxWidth='450px'
            textAlign='center'
            boxShadow='lg'
            background='gray.700'
            borderRadius='6px'>

            <Heading>
              <text color='gray.200' fontSize='2xl'>
                Registro de formulário
              </text>
            </Heading>

            <Box>
              <form action="" autoComplete='off' onSubmit={handleSubmit(onSubmit)}>
                <Flex justify='space-between'>

                  <FormControl marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Nome</FormLabel>
                    <Input
                      type='text'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Nome'
                      {...register('firstName')}
                    />
                    <p style= {{color: 'red'}}>{errors?.firstName?.message}</p>
                  </FormControl>

                  <FormControl marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Sobrenome</FormLabel>
                    <Input
                      type='text'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Sobrenome'
                      {...register('lastName')}
                    />
                    <p style= {{color: 'red'}}>{errors?.lastName?.message}</p>
                  </FormControl>
                </Flex>

                <FormControl marginTop='15px'>
                  <FormLabel color='gray.200'>E-mail</FormLabel>
                  <Input
                    border='none'
                    outline='none'
                    bgColor='gray.900'
                    focusBorderColor='gray.600'
                    color='gray.200'
                    placeholder='E-mail'
                    {...register('email')}
                  />
                  <p style= {{color: 'red'}}>{errors?.email?.message}</p>
                </FormControl>

                <Flex justify='space-between' >
                  <FormControl marginTop='15px' width='49%' >
                    <FormLabel color='gray.200'>Endereço</FormLabel>
                    <Input
                      type='address'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Endereço'
                      {...register('address')}
                    />
                    <p style= {{color: 'red'}}>{errors?.address?.message}</p>
                  </FormControl>

                  <FormControl marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Telefone</FormLabel>
                    <Input
                      type='phone'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Telefone' 
                      {...register('phone')}
                      />
                      <p style= {{color: 'red'}}>{errors?.phone?.message}</p>
                  </FormControl>
                </Flex>

                <FormControl marginTop='15px'>
                  <FormLabel color='gray.200'>Descreva sua mensagem</FormLabel>
                  <Textarea
                    border='none'
                    outline='none'
                    bgColor='gray.900'
                    focusBorderColor='gray.600'
                    color='gray.200'
                    placeholder='Descreva sua mensagem' 
                    {...register('description')}
                    />
                    <p style= {{color: 'red'}}>{errors?.description?.message}</p>
                </FormControl>

                <Button
                  type='submit'
                  width='full'
                  bgColor='green.400'
                  mt={4}
                  color='gray.200'
                  _hover={{
                    color: 'blanck'
                  }}
                >Registrar</Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  );
}


export default Cadastro;