import { 
  Box, 
  Button, 
  Flex, 
  FormControl, 
  FormHelperText, 
  FormLabel, 
  Heading, 
  Input, 
  Textarea
 } from "@chakra-ui/react";
import Head from "next/head";
import { FormEvent, FunctionComponent, useState } from "react";
import { useForm } from "react-hook-form";

interface IHomeProps{
  fistName: string;
  lastName: string;
  email: string;
  address: string;
  phone: number | null;
  description: string;
  onSubmit: () => void;
  handleSubmit: () => void;
}

const Cadastro: FunctionComponent <IHomeProps> = () => {
    const {register,handleSubmit} = useForm ()
    const onSubmit = (data: Object) => {
        console.log(data)
    }

  return (
    <>
      <Head>
        <title>Formulário com NextJs e Chacka UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex
          minHeight='100vh'
          width='full'
          align='center'
          justify='center'
          background='gray.900'

        >
          <Box
            px={12}
            py={12}
            width='full'
            maxWidth='450px'
            textAlign='center'
            boxShadow='lg'
            background='gray.700'
            borderRadius='6px'>
            <Heading color='gray.200' fontSize='2xl'>
              <text>
                Registro de formulário
              </text>
            </Heading>

            <Box>
              <form action="" autoComplete='off' onSubmit={handleSubmit(onSubmit)}>
                <Flex justify='space-between'>

                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Nome</FormLabel>
                    <Input
                      type='text'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Nome'
                      {...register('fistName')}
                    />

                  </FormControl>

                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Sobrenome</FormLabel>
                    <Input
                      type='text'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Sobrenome'
                      {...register('lastName')}
                    />
                  </FormControl>
                </Flex>

                <FormControl isRequired marginTop='15px'>
                  <FormLabel color='gray.200'>E-mail</FormLabel>
                  <Input
                    border='none'
                    outline='none'
                    bgColor='gray.900'
                    focusBorderColor='gray.600'
                    color='gray.200'
                    placeholder='E-mail'
                    {...register('email')}
                  />
                </FormControl>

                <Flex justify='space-between' >
                  <FormControl isRequired marginTop='15px' width='49%' >
                    <FormLabel color='gray.200'>Endereço</FormLabel>
                    <Input
                      type='address'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Endereço'
                      {...register('address')}
                    />
                  </FormControl>

                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Telefone</FormLabel>
                    <Input
                      type='phone'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Telefone' 
                      {...register('phone')}
                      />
                  </FormControl>
                </Flex>

                <FormControl isRequired marginTop='15px'>
                  <FormLabel color='gray.200'>Descreva sua mensagem</FormLabel>
                  <Textarea
                    border='none'
                    outline='none'
                    bgColor='gray.900'
                    focusBorderColor='gray.600'
                    color='gray.200'
                    placeholder='Descreva sua mensagem' 
                    {...register('description')}
                    />
                </FormControl>

                <Button
                  type='submit'
                  width='full'
                  bgColor='green.400'
                  mt={4}
                  color='gray.200'
                  _hover={{
                    color: 'blanck'
                  }}
                >Registrar</Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  );
}


export default Cadastro;