import { 
  Box, 
  Button, 
  Flex, 
  FormControl, 
  FormHelperText, 
  FormLabel, 
  Heading, 
  Input, 
  Textarea
 } from "@chakra-ui/react";
import Head from "next/head";



export default function Home() {
  return (
    <>
      <Head>
        <title>Formulário com NextJs e Chacka UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Flex
          minHeight='100vh'
          width='full'
          align='center'
          justify='center'
          background='gray.900'

        >
          <Box
            px={12}
            py={12}
            width='full'
            maxWidth='450px'
            textAlign='center'
            boxShadow='lg'
            background='gray.700'
            borderRadius='6px'>
            <Heading color='gray.200' fontSize='2xl'>
              <text>
                Registro de formulário
              </text>
            </Heading>
            <Box>
              <form action="" autoComplete='off'>

                <Flex justify='space-between'>
                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Nome</FormLabel>
                    <Input
                      type='text'
                      name='name'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Nome'
                    />

                  </FormControl>

                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Sobrenome</FormLabel>
                    <Input
                      type='text'
                      name="Last name"
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Sobrenome'
                    />
                  </FormControl>
                </Flex>

                <FormControl isRequired marginTop='15px'>
                  <FormLabel color='gray.200'>E-mail</FormLabel>
                  <Input
                    type='email'
                    border='none'
                    outline='none'
                    bgColor='gray.900'
                    focusBorderColor='gray.600'
                    color='gray.200'
                    placeholder='E-mail'
                  />
                </FormControl>

                <Flex justify='space-between' >
                  <FormControl isRequired marginTop='15px' width='49%' >
                    <FormLabel color='gray.200'>Endereço</FormLabel>
                    <Input
                      type='email'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Endereço'
                    />
                  </FormControl>

                  <FormControl isRequired marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Telefone</FormLabel>
                    <Input type='email'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Telefone' />
                  </FormControl>
                </Flex>

                <FormControl isRequired marginTop='15px'>
                  <FormLabel color='gray.200'>Descreva sua mensagem</FormLabel>
                  <Textarea
                    outline='none'
                    bgColor='gray.900'
                    focusBorderColor='gray.600'
                    color='gray.200'
                    placeholder='Descreva sua mensagem' />
                </FormControl>

                <Button
                  type='submit'
                  width='full'
                  bgColor='green.400'
                  mt={4}
                  color='gray.200'
                  _hover={{
                    color: 'blanck'
                  }}
                >Registrar</Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  );
}
